[package]
name = "testy-rusty"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rusttype = "0.9.3"
once_cell = "1.19.0"
lazy_static = { version = "1.4.0", features = [] }
rayon = { version = "1.8.1", features = [] }
minifb = "0.25.0"

[profile.release]
debug = 1
opt-level = 3
